fix errors during installation

diff --git a/nix-gl-installer b/nix-gl-installer
--- a/nix-gl-installer
+++ b/nix-gl-installer
@@ -172,7 +172,9 @@ install() {
   installed_script_location="$install_location/$(basename "$THIS_SCRIPT")"
   
   sudo mkdir -p "$install_location" || die "Failed to create install directory."
-  sudo cp "$THIS_SCRIPT" "$install_location" || die "Failed to install this script."
+  if [[ ! $THIS_SCRIPT -ef $install_location ]]; then
+    sudo cp "$THIS_SCRIPT" "$install_location" || die "Failed to install this script."
+  fi
   sudo chmod +x "$installed_script_location"
   sudo ln -snf "$driver_path" "$install_location/opengl-driver" || die "Failed to create symbolic link to driver."
   sudo nix-store --add-root "$install_location/opengl-driver" -r "$driver_path" > /dev/null || die "Failed to add driver to gcroot."
